"""SE3 轮腿机器人共享配置。

训练（se3_train）和验证（se3_sim2sim）的单一参数来源。
"""

from .action_delay import ActionDelayConfig, delay_seconds_to_steps
from .action_history import (
    FRONT_ACTION_INDICES,
    FRONT_ACTION_PERIOD,
    FRONT_PHYSICAL_PERIOD,
    front_action_period_from_scale,
    front_action_periods_from_scales,
    periodic_policy_action_delta_np,
    periodic_policy_action_delta_torch,
    periodic_policy_action_second_difference_np,
    periodic_policy_action_second_difference_torch,
    wrap_front_action_delta_np,
    wrap_front_action_delta_torch,
    wrap_front_action_value_delta_np,
    wrap_front_action_value_delta_torch,
)
from .fourbar import (
    FOURBAR_SURROGATE_MARKER,
    is_fourbar_surrogate_name_set,
    output_leg_length_limits_torch,
    output_leg_wheel_xz_np,
    output_leg_wheel_xz_torch,
    output_to_policy_pos_np,
    output_to_policy_pos_torch,
    output_to_policy_vel_np,
    output_to_policy_vel_torch,
    policy_to_output_pos_np,
    policy_to_output_pos_torch,
    policy_to_output_torque_np,
    policy_to_output_torque_torch,
    policy_to_output_vel_torch,
    wheel_xz_to_output_pos_np,
    wheel_xz_to_output_pos_torch,
)
from .height_default import policy_default_from_height_np, policy_default_from_height_torch
from .leg_policy import (
    policy_leg_phase_active_obs_np,
    policy_leg_phase_active_obs_torch,
    policy_leg_position_error_np,
    policy_leg_position_error_torch,
)
from .motor import DM8009P, M3508_C620_14, M3508_HEXROLL, MotorSpec
from .observation import ObservationConfig
from .policy_io import (
    DecodedPolicyAction,
    PolicyActionDecoder,
    PolicyObservationResult,
    build_policy_observation_np,
)
from .recovery import (
    RECOVERY_COMMAND_HEIGHT_M,
    RECOVERY_COMMAND_HEIGHT_RANGE_M,
    RECOVERY_COMMAND_LIN_VEL_X_LIMIT_MPS,
    RECOVERY_COMMAND_YAW_RATE_LIMIT_RAD_S,
    RECOVERY_DEFAULT_COMMAND_8D,
    RECOVERY_DEFAULT_STM_COMMAND_5D,
)
from .robot import Joint, JointGroup, RobotConfig, Termination

__all__ = [
    "DM8009P",
    "FOURBAR_SURROGATE_MARKER",
    "FRONT_ACTION_INDICES",
    "FRONT_ACTION_PERIOD",
    "FRONT_PHYSICAL_PERIOD",
    "M3508_C620_14",
    "M3508_HEXROLL",
    "RECOVERY_COMMAND_HEIGHT_M",
    "RECOVERY_COMMAND_HEIGHT_RANGE_M",
    "RECOVERY_COMMAND_LIN_VEL_X_LIMIT_MPS",
    "RECOVERY_COMMAND_YAW_RATE_LIMIT_RAD_S",
    "RECOVERY_DEFAULT_COMMAND_8D",
    "RECOVERY_DEFAULT_STM_COMMAND_5D",
    "ActionDelayConfig",
    "DecodedPolicyAction",
    "Joint",
    "JointGroup",
    "MotorSpec",
    "ObservationConfig",
    "PolicyActionDecoder",
    "PolicyObservationResult",
    "RobotConfig",
    "Termination",
    "build_policy_observation_np",
    "delay_seconds_to_steps",
    "front_action_period_from_scale",
    "front_action_periods_from_scales",
    "is_fourbar_surrogate_name_set",
    "output_leg_length_limits_torch",
    "output_leg_wheel_xz_np",
    "output_leg_wheel_xz_torch",
    "output_to_policy_pos_np",
    "output_to_policy_pos_torch",
    "output_to_policy_vel_np",
    "output_to_policy_vel_torch",
    "periodic_policy_action_delta_np",
    "periodic_policy_action_delta_torch",
    "periodic_policy_action_second_difference_np",
    "periodic_policy_action_second_difference_torch",
    "policy_default_from_height_np",
    "policy_default_from_height_torch",
    "policy_leg_phase_active_obs_np",
    "policy_leg_phase_active_obs_torch",
    "policy_leg_position_error_np",
    "policy_leg_position_error_torch",
    "policy_to_output_pos_np",
    "policy_to_output_pos_torch",
    "policy_to_output_torque_np",
    "policy_to_output_torque_torch",
    "policy_to_output_vel_torch",
    "wheel_xz_to_output_pos_np",
    "wheel_xz_to_output_pos_torch",
    "wrap_front_action_delta_np",
    "wrap_front_action_delta_torch",
    "wrap_front_action_value_delta_np",
    "wrap_front_action_value_delta_torch",
]
