"""本任务使用的奖励函数。"""

from __future__ import annotations

from mjlab.envs.mdp.rewards import is_alive

from se3_train.mdp.jump_rewards import (
    action_smoothness_no_jump,
    flat_base_lin_vel_z_no_jump,
    flat_wheel_center_alignment_no_jump,
    flat_wheel_contact_penalty_no_jump,
    flat_wheel_ground_slip_no_jump,
    idle_wheel_motion_penalty_no_jump,
)
from se3_train.mdp.rewards import (
    action_rate,
    ang_vel_xy,
    angular_momentum,
    bad_tilt,
    collision,
    command_velocity_error,
    contact_forces,
    dof_pos_limits,
    feet_contact_without_cmd,
    flat_base_height_penalty_no_jump,
    flat_leg_contact_penalty,
    flat_wheel_contact_penalty,
    joint_mirror,
    joint_pos_penalty,
    leg_dof_acc,
    leg_power,
    leg_torques,
    lin_vel_z,
    same_feet_x_position,
    stand_still,
    tracking_ang_vel,
    tracking_lin_vel,
    tracking_lin_yaw_joint,
    tracking_orientation_l2,
    wheel_torques,
)

__all__ = [
    "action_rate",
    "action_smoothness_no_jump",
    "ang_vel_xy",
    "angular_momentum",
    "bad_tilt",
    "collision",
    "command_velocity_error",
    "contact_forces",
    "dof_pos_limits",
    "feet_contact_without_cmd",
    "flat_base_height_penalty_no_jump",
    "flat_base_lin_vel_z_no_jump",
    "flat_leg_contact_penalty",
    "flat_wheel_center_alignment_no_jump",
    "flat_wheel_contact_penalty",
    "flat_wheel_contact_penalty_no_jump",
    "flat_wheel_ground_slip_no_jump",
    "idle_wheel_motion_penalty_no_jump",
    "is_alive",
    "joint_mirror",
    "joint_pos_penalty",
    "leg_dof_acc",
    "leg_power",
    "leg_torques",
    "lin_vel_z",
    "same_feet_x_position",
    "stand_still",
    "tracking_ang_vel",
    "tracking_lin_vel",
    "tracking_lin_yaw_joint",
    "tracking_orientation_l2",
    "wheel_torques",
]
