"""FlowMatch task 组使用的奖励函数。"""

from __future__ import annotations

from mjlab.envs.mdp.rewards import is_terminated

from se3_train.mdp.jump_rewards import (
    flat_base_height_penalty_no_jump,
    jump_ang_vel_xy,
    jump_landing_recovery,
    jump_orientation,
    jump_takeoff_drive,
    jump_takeoff_vz_tracking,
    jump_vel_encourage,
)
from se3_train.mdp.rewards import (
    action_rate,
    ang_vel_xy,
    bad_tilt,
    dof_pos_limits,
    leg_dof_acc,
    leg_power,
    leg_torques,
    lin_vel_z,
    tracking_ang_vel_l2,
    tracking_orientation_l2,
)
from se3_train.mdp.task_mode_rewards import (
    gait_action_smoothness,
    gait_air_time,
    gait_alternating_air_time,
    gait_leg_contact_force,
    gait_leg_idle_penalty,
    gait_low_base_height_barrier,
    gait_natural_swing_clearance,
    gait_no_wheel_drive,
    gait_short_air_time_penalty,
    gait_single_support_air_time,
    gait_single_support_contact,
    gait_stuck_stance_penalty,
    gait_swing_side_balance_penalty,
    gait_touchdown_softness,
    gait_touchdown_support_alignment,
    gait_wheel_velocity_assist,
    leg_obstacle_collision,
    loco_ang_vel_xy,
    loco_base_height,
    loco_dof_pos_limit_cost,
    loco_dof_vel_limit_cost,
    loco_lin_vel_z,
    loco_orientation,
    loco_torque_limit_cost,
    mode_stand_still,
    mode_tracking_ang_vel,
    mode_tracking_lin_vel,
    wheel_feet_distance,
    wheel_stumble,
    wheel_swing_clearance,
)

__all__ = [
    "action_rate",
    "ang_vel_xy",
    "bad_tilt",
    "dof_pos_limits",
    "flat_base_height_penalty_no_jump",
    "gait_action_smoothness",
    "gait_air_time",
    "gait_alternating_air_time",
    "gait_leg_contact_force",
    "gait_leg_idle_penalty",
    "gait_low_base_height_barrier",
    "gait_natural_swing_clearance",
    "gait_no_wheel_drive",
    "gait_short_air_time_penalty",
    "gait_single_support_air_time",
    "gait_single_support_contact",
    "gait_stuck_stance_penalty",
    "gait_swing_side_balance_penalty",
    "gait_touchdown_softness",
    "gait_touchdown_support_alignment",
    "gait_wheel_velocity_assist",
    "is_terminated",
    "jump_ang_vel_xy",
    "jump_landing_recovery",
    "jump_orientation",
    "jump_takeoff_drive",
    "jump_takeoff_vz_tracking",
    "jump_vel_encourage",
    "leg_dof_acc",
    "leg_obstacle_collision",
    "leg_power",
    "leg_torques",
    "lin_vel_z",
    "loco_ang_vel_xy",
    "loco_base_height",
    "loco_dof_pos_limit_cost",
    "loco_dof_vel_limit_cost",
    "loco_lin_vel_z",
    "loco_orientation",
    "loco_torque_limit_cost",
    "mode_stand_still",
    "mode_tracking_ang_vel",
    "mode_tracking_lin_vel",
    "tracking_ang_vel_l2",
    "tracking_orientation_l2",
    "wheel_feet_distance",
    "wheel_stumble",
    "wheel_swing_clearance",
]
